spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: liaowenqiang
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true