spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: liaowenqiang
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true